/** Auto-generated by ./scripts/deploy-surfpool.sh — do not edit manually */
export const CA_REGISTRY_PROGRAM_ID = "2WSNFu4xuaH55gpMRBN1p64YuiUXZzyze38ERXEy1U1z";
export const DIVSTRIP_PROGRAM_ID = "A36nL7RVFp8KFWQdWmmS8wTnws1NoR3Vb4cbmChyhexz";
