/**
 * Sync program IDs from Anchor.toml into generated TS + web IDL copies.
 * Run after anchor deploy (see deploy-surfpool.sh).
 */
import * as fs from "node:fs";
import * as path from "node:path";

const root = path.join(__dirname, "../..");
const anchorToml = fs.readFileSync(path.join(root, "Anchor.toml"), "utf8");

function readProgramId(name: string): string {
  const re = new RegExp(`${name}\\s*=\\s*"([^"]+)"`);
  const match = anchorToml.match(re);
  if (!match) {
    throw new Error(`Program ${name} not found in Anchor.toml`);
  }
  return match[1]!;
}

const caRegistry = readProgramId("ca_registry");
const divstrip = readProgramId("divstrip");

const generated = `/** Auto-generated by ./scripts/deploy-surfpool.sh — do not edit manually */
export const CA_REGISTRY_PROGRAM_ID = "${caRegistry}";
export const DIVSTRIP_PROGRAM_ID = "${divstrip}";
`;

const generatedPath = path.join(__dirname, "../src/lib/program-ids.generated.ts");
fs.writeFileSync(generatedPath, generated);

for (const [file, id] of [
  ["ca_registry.json", caRegistry],
  ["divstrip.json", divstrip],
] as const) {
  const idlPath = path.join(__dirname, "../src/lib", file);
  const idl = JSON.parse(fs.readFileSync(idlPath, "utf8")) as { address?: string };
  idl.address = id;
  fs.writeFileSync(idlPath, `${JSON.stringify(idl, null, 2)}\n`);
}

console.log(`Synced program IDs → ${path.relative(root, generatedPath)}`);
console.log(`  ca_registry  ${caRegistry}`);
console.log(`  divstrip     ${divstrip}`);
